name: Generate Snake Animation

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

permissions:
  contents: write  # Allows pushing changes

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # We will use GITHUB_TOKEN instead

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Jithu-SM
          outputs: dist/github-contribution-grid-snake.svg

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's built-in token
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated snake animation" || echo "Nothing to commit"
          git push origin main
